---
# Basic provisioning example
- name: Create AWS resources
  hosts: localhost
  connection: local
  strategy: debug
  vars_files:
    - config_vars/{{ instance_type }}
  gather_facts: False
  tasks:

  - name: Get public IP address for this computer
    ipify_facts:
    register: my_public_ip

  - name: Create a security group
    ec2_group:
      name: realrl_local_ssh
      description: "Security Group for RealRL server allowing SSH only from local IP"
      region: "{{ aws_region }}"
      vpc_id: "{{ vpc_id }}"
      # aws_access_key: # Uses environment variable $AWS_ACCESS_KEY_ID
      # aws_secret_key: # Uses environment variable $AWS_SECRET_ACCESS_KEY
      rules:
        - proto: tcp
          ports: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          ports: 22
          cidr_ip: "{{ ipify_public_ip + '/32' }}"
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: firewall

  - name: Create an EC2 instance
    ec2:
      # aws_access_key: # Uses environment variable $AWS_ACCESS_KEY_ID
      # aws_secret_key: # Uses environment variable $AWS_SECRET_ACCESS_KEY
      key_name: "{{ ssh_key_name }}"
      region: "{{ aws_region }}"
      #zone:  "{{ aws_zone }}"
      group_id: "{{ firewall.group_id }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      instance_tags:
        type: deep_aws
      exact_count: 1
      count_tag:
        type: deep_aws
      spot_price: "{{ spot_price }}"
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      port: 22
      state: started
    with_items: "{{ ec2.instances }}"


# ------ Run Setup on the EC2 Instances --------- #
- hosts: aws_ec2
  vars:
    ansible_host_key_checking: false
    ansible_ssh_private_key_file: "~/.ssh/{{ ssh_key_name }}.pem"
  remote_user: ec2-user
  #become: yes
  gather_facts: no
  tasks:
  - name: Upload GitHub SSH key
    copy:
        src: ~/.ssh/github_rsa
        dest: ~/.ssh/
        owner: ec2-user
        group: ec2-user
        mode: 0600
  - name: Upload Project Specific SSH Keys
    copy:
        src: remote_files/
        dest: ~/.ssh/
        owner: ec2-user
        group: ec2-user
        mode: 0600
  - name: 'install python3 and git'
    raw: 'sudo yum install python3 -y'
    raw: 'sudo yum install git -y'
  - name: Clone the RealRL repository
    git:
        repo: git@github.com:theforager/Bonsai.git
        dest: ~/Bonsai
        key_file: ~/.ssh/github_rsa
